# K.V.N project setup (Windows) — the PowerShell sibling of scripts/setup.sh.
#
#   .\scripts\setup.ps1          # everything needed to RUN the project
#   .\scripts\setup.ps1 -Dev     # the above PLUS dev tooling + docs deliverables
#
# Creates the .venv, installs the package + extras, and drops a `kvn.bat` launcher
# on your PATH so you can run the CLI as plain `kvn` (no `uv run`) from any
# directory. Idempotent: safe to re-run (e.g. after the repo moves, to repoint the
# launcher). Mirrors setup.sh; the Windows copy is a run target, so this skips the
# git hooks (you never commit from here).
#
# Python is pinned to 3.12 by the repo's .python-version — numpy 1.26.4 has no
# Windows wheel for 3.13, so a newer interpreter would try to compile it and fail.
param([switch]$Dev)
$ErrorActionPreference = "Stop"
$RepoRoot = Split-Path -Parent $PSScriptRoot

if (-not (Get-Command uv -ErrorAction SilentlyContinue)) {
    Write-Error "uv is not installed. See https://github.com/astral-sh/uv"
}

# Extras, in two tiers (same as setup.sh). EXTRAS env var overrides both.
$RunExtras = "ml,stereo-input,viz,scenegen,cli"
$DevExtras = "dev,docs"
$Extras = if ($env:EXTRAS) { $env:EXTRAS }
          elseif ($Dev) { "$RunExtras,$DevExtras" }
          else { $RunExtras }

Push-Location $RepoRoot
try {
    Write-Host "==> Creating virtualenv (.venv, Python 3.12) and installing .[$Extras] ..."
    uv python install 3.12          # no-op if already present
    uv venv --python 3.12           # also honoured by the committed .python-version
    uv pip install -e ".[$Extras]"

    # Launcher: a kvn.bat that calls THIS clone's venv interpreter via
    # `-m ai_teleop.cli` — the interpreter path, not the console-script shim, so it
    # keeps working if the .venv is relocated (same rationale as setup.sh).
    # WindowsApps is on the user PATH by default, so no PATH edit is needed.
    $BinDir = if ($env:KVN_BIN_DIR) { $env:KVN_BIN_DIR } else { "$env:LOCALAPPDATA\Microsoft\WindowsApps" }
    New-Item -ItemType Directory -Force -Path $BinDir | Out-Null
    $Launcher = Join-Path $BinDir "kvn.bat"
    $Python = Join-Path $RepoRoot ".venv\Scripts\python.exe"
    @"
@echo off
REM Auto-generated by scripts/setup.ps1 — launches the K.V.N CLI for this clone.
REM Re-run scripts/setup.ps1 after moving the repo to repoint this.
"$Python" -m ai_teleop.cli %*
"@ | Set-Content -Encoding Ascii -Path $Launcher
    Write-Host "==> Installed launcher: $Launcher"

    if (($env:PATH -split ';') -contains $BinDir) {
        Write-Host "==> Done. Open a new terminal, then:  kvn --help"
    } else {
        Write-Host "==> Done, but '$BinDir' is NOT on your PATH. Add it (User env vars), or use:"
        Write-Host "      uv run kvn        (from $RepoRoot)"
    }
}
finally {
    Pop-Location
}
