#!/usr/bin/env bash
# K.V.N project setup — run once after cloning.
#
#   ./scripts/setup.sh          # everything needed to RUN the project
#   ./scripts/setup.sh --dev    # the above PLUS dev tooling + docs deliverables
#
# Creates the .venv, installs the package + extras, enables the git hooks, and
# drops a `kvn` launcher on your PATH so you can run the CLI as plain `kvn` (no
# `uv run`) from any directory. Idempotent: safe to re-run (e.g. after the repo
# moves, to repoint the launcher).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

if ! command -v uv >/dev/null 2>&1; then
  echo "FATAL: uv is not installed. See https://github.com/astral-sh/uv" >&2
  exit 1
fi

DEV=0
for arg in "$@"; do
  case "$arg" in
    -D|--dev) DEV=1 ;;
    -h|--help)
      sed -n '2,9p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *) echo "FATAL: unknown argument '$arg' (use -D/--dev or -h/--help)" >&2; exit 2 ;;
  esac
done

# Extras, in two tiers:
#   run  — everything needed to actually run the project: policy train/eval (ml),
#          stereo two-webcam teleop (stereo-input, pulls stereohand), episode
#          recording (viz), procedural scene generation (scenegen), rich logging (cli).
#   dev  — also dev tooling (pytest/ruff/mypy/poe) and the D1 docs deliverables.
RUN_EXTRAS="ml,stereo-input,viz,scenegen,cli"
DEV_EXTRAS="dev,docs"
if [[ "$DEV" == "1" ]]; then
  DEFAULT_EXTRAS="$RUN_EXTRAS,$DEV_EXTRAS"
else
  DEFAULT_EXTRAS="$RUN_EXTRAS"
fi
# EXTRAS env var overrides the tiers entirely (and takes precedence over --dev).
EXTRAS="${EXTRAS:-$DEFAULT_EXTRAS}"

# `uv sync` installs the exact versions pinned in uv.lock (reproducible across
# machines), creating .venv and installing the project editable. Do NOT use
# `uv pip install` here: it re-resolves from scratch and can pick different versions
# per platform — e.g. on Windows it resolved an old cadquery→numba→llvmlite that
# won't build on 3.12, while the lock pins a clean cadquery. Extras become --extra flags.
extra_args=()
IFS=',' read -ra _extras <<< "$EXTRAS"
for e in "${_extras[@]}"; do extra_args+=(--extra "$e"); done
echo "==> Creating .venv and syncing locked deps (extras: $EXTRAS) ..."
uv sync "${extra_args[@]}"

echo "==> Enabling git hooks (core.hooksPath .githooks) ..."
git config core.hooksPath .githooks

# Launcher: invoke the venv's interpreter directly via `python -m ai_teleop.cli`.
# Using the absolute interpreter path (not the console-script shebang) keeps this
# working even if the .venv is later relocated — see kevin/CLAUDE.md.
BIN_DIR="${KVN_BIN_DIR:-$HOME/.local/bin}"
LAUNCHER="$BIN_DIR/kvn"
mkdir -p "$BIN_DIR"
cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Auto-generated by kevin/scripts/setup.sh — launches the K.V.N CLI for this clone.
# Re-run scripts/setup.sh after moving the repo to repoint this.
exec "$REPO_ROOT/.venv/bin/python" -m ai_teleop.cli "\$@"
EOF
chmod +x "$LAUNCHER"
echo "==> Installed launcher: $LAUNCHER"

case ":$PATH:" in
  *":$BIN_DIR:"*)
    echo "==> Done. '$BIN_DIR' is on your PATH — try:  kvn"
    ;;
  *)
    echo "==> Done, but '$BIN_DIR' is NOT on your PATH. Add it, then restart your shell:"
    echo "      echo 'export PATH=\"$BIN_DIR:\$PATH\"' >> ~/.zshrc"
    echo "    Until then, use:  uv run kvn   (from $REPO_ROOT)"
    ;;
esac
