#!/usr/bin/env bash
# K.V.N project setup — run once after cloning.
#
#   ./scripts/setup.sh
#
# Creates the .venv, installs the package + dev tooling, enables the git hooks,
# and drops a `kvn` launcher on your PATH so you can run the CLI as plain `kvn`
# (no `uv run`) from any directory. Idempotent: safe to re-run (e.g. after the
# repo moves, to repoint the launcher).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

if ! command -v uv >/dev/null 2>&1; then
  echo "FATAL: uv is not installed. See https://github.com/astral-sh/uv" >&2
  exit 1
fi

# Which extras to install. Override with EXTRAS, e.g. EXTRAS="dev,ml,vision-input".
EXTRAS="${EXTRAS:-dev}"

echo "==> Creating virtualenv (.venv) and installing .[$EXTRAS] ..."
uv venv
uv pip install -e ".[$EXTRAS]"

echo "==> Enabling git hooks (core.hooksPath .githooks) ..."
git config core.hooksPath .githooks

# Launcher: invoke the venv's interpreter directly via `python -m ai_teleop.cli`.
# Using the absolute interpreter path (not the console-script shebang) keeps this
# working even if the .venv is later relocated — see kevin/CLAUDE.md.
BIN_DIR="${KVN_BIN_DIR:-$HOME/.local/bin}"
LAUNCHER="$BIN_DIR/kvn"
mkdir -p "$BIN_DIR"
cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Auto-generated by kevin/scripts/setup.sh — launches the K.V.N CLI for this clone.
# Re-run scripts/setup.sh after moving the repo to repoint this.
exec "$REPO_ROOT/.venv/bin/python" -m ai_teleop.cli "\$@"
EOF
chmod +x "$LAUNCHER"
echo "==> Installed launcher: $LAUNCHER"

case ":$PATH:" in
  *":$BIN_DIR:"*)
    echo "==> Done. '$BIN_DIR' is on your PATH — try:  kvn"
    ;;
  *)
    echo "==> Done, but '$BIN_DIR' is NOT on your PATH. Add it, then restart your shell:"
    echo "      echo 'export PATH=\"$BIN_DIR:\$PATH\"' >> ~/.zshrc"
    echo "    Until then, use:  uv run kvn   (from $REPO_ROOT)"
    ;;
esac
